modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/architectury/ClothConfig/issues/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/"
logoFile = "icon.png"
authors = "shedaniel"
license = "GNU LGPLv3"

[[mods]]
modId = "cloth_config"
version = "${version}"
displayName = "Cloth Config v7 API"
description = '''
An API for config screens.
'''

[[dependencies.cloth_config]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"
