modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/shedaniel/cloth-config/issues/"
license = "GNU LGPLv3"

[[mods]]
modId = "cloth_config"
version = "${version}"
displayName = "Cloth Config v14 API"
displayURL = "https://modrinth.com/mod/cloth-config"
logoFile = "icon.png"
authors = "shedaniel"
description = '''
An API for config screens.
'''

[[dependencies.cloth_config]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"
