package me.shedaniel.clothconfig2.api.dependencies;

public interface DependencyBuilder<SELF extends DependencyBuilder<SELF>> {
    
    /**
     * Disable auto-generating of tooltips by the dependency.
     * If this is used, it is strongly recommended to implement your own tooltip or label text explaining the
     * dependency to your end-users.
     * 
     * @return this instance, for chaining
     * @see #generateTooltip(boolean) 
     */
    default SELF withoutTooltip() {
        return generateTooltip(false);
    }
    
    /**
     * Set whether a tooltip should be auto-generated or not by the dependency.
     * If not, it is strongly recommended to implement your own tooltip or label text explaining the dependency
     * to your end-users.
     * 
     * @param shouldGenerate whether a tooltip should be auto-generated by the dependency
     * @return this instance, for chaining
     * @see #withoutTooltip()
     */
    SELF generateTooltip(boolean shouldGenerate);
}
