plugins {
    id "com.gradleup.shadow" version "9.4.2"
    id "maven-publish"
}

loom {
    accessWidenerPath = file("src/main/resources/cloth-config.accessWidener")
}

configurations {
    shadowCommon
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.architectury.minecraft}"
    // We depend on fabric loader here to use the fabric @Environment annotations
    // Do NOT use other classes from fabric loader
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    api("me.shedaniel.cloth:basic-math:0.6.1")

    compileOnly("blue.endless:jankson:${rootProject.jankson_version}")
    compileOnly("com.moandjiezana.toml:toml4j:${rootProject.toml4j_version}")
    compileOnly("org.yaml:snakeyaml:${rootProject.snakeyaml_version}")
    shadowCommon("blue.endless:jankson:${rootProject.jankson_version}")
    shadowCommon("com.moandjiezana.toml:toml4j:${rootProject.toml4j_version}") {
        exclude(module: "gson")
    }
    shadowCommon("org.yaml:snakeyaml:${rootProject.snakeyaml_version}")
}

architectury {
    common("fabric", /*"forge", */"neoforge")
}

jar {
    archiveClassifier = "raw"
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    relocate "blue.endless.jankson", "${rootProject.maven_group}.clothconfig.shadowed.blue.endless.jankson"
    relocate "com.moandjiezana.toml", "${rootProject.maven_group}.clothconfig.shadowed.com.moandjiezana.toml"
    relocate "org.yaml.snakeyaml", "${rootProject.maven_group}.clothconfig.shadowed.org.yaml.snakeyaml"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    from rootProject.file("LICENSE.md")
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    repositories {
        if (System.getenv("MAVEN_PASS") != null) {
            maven {
                url = "https://deploy.shedaniel.me/"
                credentials {
                    username = "shedaniel"
                    password = System.getenv("MAVEN_PASS")
                }
            }
        }
    }
}
