modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/shedaniel/cloth-config/issues/"
license = "GNU LGPLv3"

[[mods]]
modId = "cloth_config"
version = "${version}"
displayName = "Cloth Config v26.2 API"
displayURL = "https://modrinth.com/mod/cloth-config"
iconFile = "icon.png"
authors = "shedaniel"
description = '''
An API for config screens.
'''

[[dependencies.cloth_config]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.0-beta,)"
ordering = "NONE"
side = "BOTH"
